version: '2'

services:
  iex:
    build: .
    command: 'iex'
    volumes:
      - .:/home/elixir-learning
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: '/home/elixir-learning'

  exercism:
    build: ./exercism
    volumes:
      - ./exercism:/home/exercism
    working_dir: '/exercism'

